### ISSUE TITLE
Model/Sensor/State interface is inconsistent (imho) after failed initialization

### ISSUE THREAD

**Issue by francesco-romano** [robotology/yarp-wholebodyinterface#14]
This issue refers to the actuator, but probably it affects also the other components.

When an initialization fails (e.g. failed to open drivers) all arrays used in the object have already been resized to the proper dimensions.
In all the methods, checks on the array size are done, but not on their content, thus causing possible segfaults if methods are called on a not initialized object.
Solutions that come to my mind are:
- in case of failed init revert the sizes to 0
- check in every method the boolean `initDone` variable.
- do more checks on each variable.

I think the first one is the cleanest solution. Of course, user of the interface should not call if init is false (btw: we should add  a getter for it), but we should also be robust to misuses. 
cc @traversaro

**Comment by francesco-romano** [comment]
@traversaro  I only changed the actuator, not the other classes

**Comment by traversaro** [comment]
As yarp-wholebodyinterface has been deprecated, we will not solve this issue.
