### ISSUE TITLE
Torque measurements equal to zero for about 30 ms

### ISSUE THREAD

**Issue by DanielePucci** [robotology/yarp-wholebodyinterface#17]
When I launch a getTorque (for instance from the WBIToolbox), the torque measurement is equal to zero for about 30 ms. This in turn causes jerky robot's movements associated with any torque controller, since as soon as the non-zero reference arrives to the low-level controller, the voltages applied to the motors will be subject to relatively big jumps.

**Comment by DanielePucci** [comment]
This issue is most likely related to #18

**Comment by francesco-romano** [comment]
Closing.
