### ISSUE TITLE
Optimize setControlMode implementation

### ISSUE THREAD

**Issue by traversaro** [robotology/yarp-wholebodyinterface#18]
Currently the setControlMode implementation is slow (it was part of a trade off for simplicity and having a fast setControlReference).

**Comment by randaz81** [comment]
Beware: on the real robot the low level setControlMode() may take several tens of milliseconds to be executed and the method is intentional blocking.

**Comment by traversaro** [comment]
Yes, the point is to implement it using the multi axis methods provided by the IControlMode2 interface.

**Comment by traversaro** [comment]
As yarp-wholebodyinterface has been deprecated, we will not solve this issue. Please use the  multiple-axis method of the YARP's IControlMode interface (
`yarp::dev::IControlMode::setControlModes(const int n_joint, const int *joints, int *modes)`, see 
https://www.yarp.it/classyarp_1_1dev_1_1IControlMode.html#a24322b7b0c6e707e7ee29acd2e8f4c05) to efficiently change the control mode of the joints, and make sure there is no bottleneck of this in your YARP robot.
