### ISSUE TITLE
[states] yarpWholeBodyEstimator seems to have a lot of jitter

### ISSUE THREAD

**Issue by traversaro** [robotology/yarp-wholebodyinterface#32]
cc @DanielePucci 
This could be related to a lot of contentions of the `mutex` semaphore. Reducing the number of operations in the critical region could help for sure.

**Comment by DanielePucci** [comment]
Thanks.

**Comment by traversaro** [comment]
The main problem is that the `yarpWholeBodyEstimator` for a lot of measurements is just copying the data from the `RemoteControlBoard`  buffer to its buffer, and then the `getEstimates` calls are accessing the `yarpWholeBodyEstimator` buffers. To avoiding delays and jitter, for a lot of estimates (joint pos/vel/acc/torques and motor stuff) it would make a lot of sense for the `getEstimates` calls directly access the `RemoteControlBoard` buffer, by calling the appropriate method. `yarpWholeBodyEstimator` would just remain for estimates that need some processing (such as filters).
 Anyway on the long term I think that it would make sense to  move all filtering stuff to ad-hoc portmonitors.

**Comment by traversaro** [comment]
As yarp-wholebodyinterface has been deprecated, we will not solve this issue. The current recommendation is to avoid to include this application specific filtering or estimation in interfaces such as yarp-wholebodyinterface, but rather try to reduce as much as possible the threads that compose your robot controller, to avoid having non-deterministic problems caused by relying on the operating system scheduler.
