### ISSUE TITLE
Matlab internal problem relative to WB-Toolbox estimator

### ISSUE THREAD

**Issue by pi-q** [robotology/yarp-wholebodyinterface#54]
I tried to run a simulation from Simulink to Gazebo, in which the only block is the "Get estimate" from WB-Toolbox (set to Joint Positions). After compiling, instead of starting the simulation, Matlab crashes with the following error: "MATLAB has encountered an internal problem and needs to close." See below for the full details related to the error.

However, adding the line "readSpeedAccFromControlBoard" in yarpWholeBodyInterface.ini solves the problem. Could there be an issue with the estimator?

---

```
   Segmentation violation detected at Thu Jul  7 16:29:54 2016
```

---

Configuration:
  Crash Decoding      : Disabled
  Crash Mode          : continue (default)
  Current Graphics Driver: Unknown hardware 
  Current Visual      : 0x20 (class 4, depth 24)
  Default Encoding    : UTF-8
  GNU C Library       : 2.19 stable
  Host Name           : marie-Lenovo-E31-70
  MATLAB Architecture : glnxa64
  MATLAB Root         : /usr/local/MATLAB/R2015b
  MATLAB Version      : 8.6.0.267246 (R2015b)
  OpenGL              : hardware
  Operating System    : Linux 3.19.0-64-generic #72~14.04.1-Ubuntu SMP Fri Jun 24 17:59:48 UTC 2016 x86_64
  Processor ID        : x86 Family 6 Model 61 Stepping 4, GenuineIntel
  Virtual Machine     : Java 1.7.0_60-b19 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
  Window System       : The X.Org Foundation (11701000), display :0

Fault Count: 1

Abnormal termination:
Segmentation violation

Register State (from fault):
  RAX = 0000000000000002  RBX = 00007f6ae77f5208
  RCX = 0000001700000003  RDX = 0000001700000004
  RSP = 00007f6ae77f5178  RBP = 00007f6ae77f51d0
  RSI = 00001fa000000017  RDI = 00007f6ae77f51fc

   R8 = 00007f6c0c1ed708   R9 = fffffffffffffc20
  R10 = fffffffffffffc10  R11 = 00007f6c0c1edaa0
  R12 = 0000000000000001  R13 = 00007f6ae77f51fc
  R14 = 00007f6c0c1ed708  R15 = 00007f6ae77f51f8

  RIP = 00007f6b194b1250  EFL = 0000000000010297

   CS = 0033   FS = 0000   GS = 0000

Stack Trace (from fault):
[  0] 0x00007f6b194b1250        /usr/local/MATLAB/R2015b/bin/glnxa64/mkl.so+19898960 mkl_blas_avx2_dnrm2+00000064
[  1] 0x00007f6b1864cf87        /usr/local/MATLAB/R2015b/bin/glnxa64/mkl.so+04808583 mkl_blas_dnrm2+00000295
[  2] 0x00007f6b1848df8e        /usr/local/MATLAB/R2015b/bin/glnxa64/mkl.so+02977678 dnrm2+00000046
[  3] 0x00007f6b0492793b                              /usr/lib/libblas.so.3+00260411 dnrm2sub_+00000011
[  4] 0x00007f6b048f7b80                              /usr/lib/libblas.so.3+00064384 cblas_dnrm2+00000032
[  5] 0x00007f6b0453bc2b                               /usr/lib/libgsl.so.0+00736299 gsl_linalg_householder_transform+00000059
[  6] 0x00007f6b04540720                               /usr/lib/libgsl.so.0+00755488 gsl_linalg_bidiag_decomp+00000544
[  7] 0x00007f6b045387ed                               /usr/lib/libgsl.so.0+00722925 gsl_linalg_SV_decomp+00000365
[  8] 0x00007f6b064bc43c                   /usr/local/lib/libYARP_math.so.1+00070716 _ZN4yarp4math3SVDERKNS_3sig6MatrixERS2_RNS1_6VectorES5_+00000732
[  9] 0x00007f6b064bd2fe                   /usr/local/lib/libYARP_math.so.1+00074494 _ZN4yarp4math4pinvERKNS_3sig6MatrixEd+00000270
[ 10] 0x00007f6b06dab6cb /home/marie/codyco-superbuild/build/install/mex/../lib/libyarpwholebodyinterface.so.0.3.2+00513739 _ZN4iCub4ctrl15AWPolyEstimator3fitERKN4yarp3sig6VectorES6_j+00000443
[ 11] 0x00007f6b06dab081 /home/marie/codyco-superbuild/build/install/mex/../lib/libyarpwholebodyinterface.so.0.3.2+00512129 _ZN4iCub4ctrl15AWPolyEstimator8estimateEv+00000977
[ 12] 0x00007f6b06dab502 /home/marie/codyco-superbuild/build/install/mex/../lib/libyarpwholebodyinterface.so.0.3.2+00513282 _ZN4iCub4ctrl15AWPolyEstimator8estimateERKNS0_13AWPolyElementE+00000034
[ 13] 0x00007f6b06d6f50a /home/marie/codyco-superbuild/build/install/mex/../lib/libyarpwholebodyinterface.so.0.3.2+00267530 _ZN7yarpWbi22yarpWholeBodyEstimator3runEv+00000250
[ 14] 0x00007f6b05d9f892                     /usr/local/lib/libYARP_OS.so.1+01374354 _ZN25RateThreadCallbackAdapter3runEv+00000610
[ 15] 0x00007f6b05ded3ed                     /usr/local/lib/libYARP_OS.so.1+01692653 _Z18theExecutiveBranchPv+00000349
[ 16] 0x00007f6afbd72b16                           /usr/lib/libACE-6.0.3.so+00940822 _ZN21ACE_OS_Thread_Adapter6invokeEv+00000134
[ 17] 0x00007f6c34751184              /lib/x86_64-linux-gnu/libpthread.so.0+00033156
[ 18] 0x00007f6c3447e37d                    /lib/x86_64-linux-gnu/libc.so.6+01024893 clone+00000109
[ 19] 0x0000000000000000                                   <unknown-module>+00000000

If this problem is reproducible, please submit a Service Request via:
    http://www.mathworks.com/support/contact_us/

A technical support engineer might contact you with further information.

Thank you for your help.

**Comment by traversaro** [comment]
I guess it was some kind of strange bug related to the estimated, that are contained in the libraries distributed by the `icub-main` repository. If the meanwhile the WB-Toolbox had two major releases, and since version 3.0 is not based on the yarp-wholebodyinterface at all. If you experience again this issue, please open a WB-Toolbox issue at: https://github.com/robotology/wb-toolbox/issues/new/choose .
