### ISSUE TITLE
/icubGazeboSim/left_leg/analog:o does not exist, thus failing yarpWholeBodySensors::init()

### ISSUE THREAD

**Issue by jeljaik** [robotology/yarp-wholebodyinterface#7]
The error can be reproduced by setting the environmental variable `YARP_ROBOT_NAME=iCubHeidelberg01` and then running `yarpWholeBodyInterfaceTest`

**Comment by francesco-romano** [comment]
I close this issue given that it is 2 years old.
If this is still a problem, please reopen it.
