### ISSUE TITLE
Remove the URDF models installed by this repo

### ISSUE THREAD

**Issue by traversaro** [robotology/yarp-wholebodyinterface#89]
Since we merged https://github.com/robotology/robotology-superbuild/pull/91 , it is  now time to remove the URDF models provide in this repo.

| YARP_ROBOT_NAME  |  Action |
|:----------:|:-------------------:|
| bigman             |   **REMOVE**: Unused and the update model is in another repo, I think we can remove it @gabrielenava     |
| bigman_only_legs   |    **REMOVE**:  Unused and the update model is in another repo, I think we can remove it @gabrielenava     |
| coman              |   **REMOVE**:  Unused and the update model is in another repo, I think we can remove it @gabrielenava      |
| comanGazeboSim  |     **REMOVE**:  Unused and the update model is in another repo, I think we can remove it @gabrielenava       |
| double_pendulum    | **REMOVE**:   This was indeed a nice example, it would nice to have it somewhere, but in the meanwhile we can just remove it. |
| iCubDarmstadt01    |  **REMOVE**:  Superseded by `icub-models`.      |
| iCubGazeboV2_5  |     **REMOVE**:  Superseded by `icub-models`.          |
| iCubGenova01      |      **REMOVE**:  Superseded by `icub-models`.       |
| iCubGenova01TEST   |    **REMOVE**: Really old test by me.        |
| iCubGenova02      |    **REMOVE**:  Superseded by `icub-models`.         |
| iCubGenova03      |    **REMOVE**:  Superseded by `icub-models`.         |
| iCubGenova04      |     **REMOVE**:  Superseded by `icub-models`.        |
| iCubGenova05      |     **REMOVE**:  There is not robot with that name.   |
| iCubHeidelberg01   |   ~~@hu-yue You think someone will use that robot in the near future? At the moment it was not ported in the icub-model-generator infrastructure~~ **REMOVE**: no  one is working with iCubHeidelberg01 at the moment  |
| iCubNancy01      |   ~~The directory contains several hand-modified models.. Are they used somewhere? Can we remove them @serena-ivaldi @InriaBrice @gabrielenava @pi-q~~ **REMOVE**:  Nancy peole have their own local URDF that they mantain themself.    |
| iCubParis01      |      **REMOVE**:  Superseded by `icub-models`.     |
| iCubParis02      |   **REMOVE**:  Superseded by `icub-models`.      |
| icubGazeboSim  |   See https://github.com/robotology/yarp-wholebodyinterface/issues/84   |

**Comment by gabrielenava** [comment]
- Regarding `bigman` and `bigman_only_legs`, the updated model is in another repo and we can remove it. 

- Regarding `ccoman` and `comanGazeboSim`, I never worked with this model. I suspect it is a leftover of ages ago.

-  Regarding `iCubNancy01`, I don't know the current status, I think it is better to wait for confirmation before deleting it.

**Comment by traversaro** [comment]
First removal handled in https://github.com/robotology/yarp-wholebodyinterface/issues/89 .

**Comment by traversaro** [comment]
Are this models compatible with the iDynTree/WB-Toolbox (joint names compatible with YARP joint names, installed in the correct YARP conf folder so that they can be found using the ResourceFinder, etc, etc), or you are not using IIT software at all? Perhaps @pi-q has more info on this.

**Comment by InriaBrice** [comment]
We are not using iDynTree/WB-Toolbox, so i have no idea if they are compatible. Also for now the version of YARP installed is still 2.73, we didn't moved to YARP 3.0.0 yet.

We have a set up based on OpenSoT and YARP.

**Comment by traversaro** [comment]
As mentioned by @InriaBrice, `iCubNancy01` people manage their own URDF, so I think we can safely drop it. I think the only remaining model to move is `icubGazeboSim`  https://github.com/robotology/yarp-wholebodyinterface/issues/84 , that for now we can just store in `icub-gazebo`.

**Comment by traversaro** [comment]
This will be fixed by https://github.com/robotology/icub-gazebo/pull/73 .

**Comment by traversaro** [comment]
Fixed by https://github.com/robotology/icub-gazebo/pull/73 .
